In [1]:
import time
import sys
sys.path.append('../../src/')

from density_map import get_density_map, get_density_image

import pandas as pd
import numpy as np
from shapely.geometry import Point, Polygon
import matplotlib.pyplot as plt
import matplotlib as mpl
mpl.rcParams['figure.dpi'] = 400

In [3]:
df = pd.read_csv('../../data/data_refined.csv')

timestamps_unique = df['timestamp'].unique()

batch = df[df['timestamp'] == timestamps_unique[55]]
batch = batch.reset_index(drop=True)
print(len(batch))
timestamp = batch['timestamp'].to_list()[0]
print(time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(timestamp)))

batch.head()

2526
2024-08-09 14:43:22


timestamp                                                mac          x  \
0  1723211002  4b006d690e1448bc79a210f1e3dd1a0d57b5252ad40a07...  65.312720   
1  1723211002  fce2659938ee27f8d03fdba73468bc61803aefa8870a98...  59.245930   
2  1723211002  43d1742ed3f83d55c8101ea798ef2f34fe0bcac1eeb76c...  89.796160   
3  1723211002  81320bdc5688346e1c531850a1a2666123f6ad57d57803...  32.119341   
4  1723211002  61ee7fe8db7d99252fcb0e766040431260c572190fe106...  36.727548   

           y         error  rssi  floor_id   room_id  
0  18.458105  1.000000e+01 -66.9       936       NaN  
1  19.626686  7.105427e-15 -69.4       935   58579.0  
2  17.610748  2.842171e-14 -51.0      1102  109865.0  
3  29.286948  5.248042e-01 -60.4       956   59410.0  
4  26.338445  2.362308e-01 -61.7      1034   66051.0

In [8]:
image_bytes = get_density_image(floor_id=1654, batch=batch)

with open('density_map.png', 'wb') as f:
    f.write(image_bytes)

138
[[[255. 255. 255.   0.]
  [255. 255. 255.   0.]
  [255. 255. 255.   0.]
  ...
  [255. 255. 255.   0.]
  [255. 255. 255.   0.]
  [255. 255. 255.   0.]]

 [[255. 255. 255.   0.]
  [255. 255. 255.   0.]
  [255. 255. 255.   0.]
  ...
  [255. 255. 255.   0.]
  [255. 255. 255.   0.]
  [255. 255. 255.   0.]]

 [[255. 255. 255.   0.]
  [255. 255. 255.   0.]
  [255. 255. 255.   0.]
  ...
  [255. 255. 255.   0.]
  [255. 255. 255.   0.]
  [255. 255. 255.   0.]]

 ...

 [[255. 255. 255.   0.]
  [255. 255. 255.   0.]
  [255. 255. 255.   0.]
  ...
  [255. 255. 255.   0.]
  [255. 255. 255.   0.]
  [255. 255. 255.   0.]]

 [[255. 255. 255.   0.]
  [255. 255. 255.   0.]
  [255. 255. 255.   0.]
  ...
  [255. 255. 255.   0.]
  [255. 255. 255.   0.]
  [255. 255. 255.   0.]]

 [[255. 255. 255.   0.]
  [255. 255. 255.   0.]
  [255. 255. 255.   0.]
  ...
  [255. 255. 255.   0.]
  [255. 255. 255.   0.]
  [255. 255. 255.   0.]]]
